### ISSUE TITLE
2024/lab1: Имя пользователя при добавлении конфигурации SSH подключения

### ISSUE THREAD

**Issue by KoJem9Ka** [kpdvstu/SOBD#1]
В [лабораторной работе №1](https://github.com/kpdvstu/SOBD/tree/main/2024/lab1#порядок-выполнения-работы) в пункте «[Порядок выполнения работы](https://github.com/kpdvstu/SOBD/tree/main/2024/lab1#порядок-выполнения-работы)» при добавлении SSH конфига в команде в атрибуте `-J` пропущен пользователь `user@`.

Шаблон команды должен быть следующий:
`ssh -J user@ip:port user@hadoop-node`

**Comment by kpdvstu** [comment]
Исправлено.
commit 3815914

**Comment by kpdvstu** [comment]
Исправлено.
commit 3815914
